# Generated by Django 5.2.8 on 2025-12-06 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_orderitem_food'),
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FoodItem',
        ),
    ]
