# Generated by Django 5.2.8 on 2025-12-15 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_delete_fooditem'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='is_popular',
            field=models.BooleanField(default=False),
        ),
    ]
