# Generated by Django 5.2.8 on 2025-12-08 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_category_image_remove_offer_discount_and_more'),
        ('restaurants', '0002_delete_fooditem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foods', to='restaurants.restaurant'),
        ),
        migrations.DeleteModel(
            name='Restaurant',
        ),
    ]
