# Generated by Django 5.2.8 on 2025-12-15 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_fooditem_restaurant_delete_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='is_trending',
            field=models.BooleanField(default=False),
        ),
    ]
