# Generated by Django 5.2.8 on 2025-12-15 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_offer_discount_amount_offer_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='discount_amount',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='min_order_amount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='applied_offer',
        ),
        migrations.RemoveField(
            model_name='order',
            name='discount',
        ),
    ]
